export { chooseBasicBotAction, chooseDiscardTile } from "./bots/basicBot.js";
export { applyAction, createEmptyPlayerView, createInitialGame, createPlayerView, getLegalActions } from "./game.js";
export type { ApplyActionResult, CreateGameOptions, MahjongGameState, PlayerState } from "./game.js";
export { canHu, countTiles, isSevenPairs } from "./hand.js";
export type { HuPattern, HuResult } from "./hand.js";
export { simpleRuleConfig, standardRuleConfig } from "./rules.js";
export type { RuleConfig } from "./rules.js";
export { calculateScore, identifyFans, isChinitsu, isHonitsu, isHonroutou, isPinfu, isTanyao, isToitoi } from "./scoring.js";
export type { Fan, FanType, ScoreOptions, ScoreResult } from "./scoring.js";
export { compareTiles, createTile, getTileDefinition, isSameTileType, tileDefinitions } from "./tiles.js";
export type { Tile, TileCode, TileDefinition } from "./tiles.js";
export { createSeededRandom, createShuffledWall, createWall, shuffleWall } from "./wall.js";
export type { RandomSource } from "./wall.js";
export { runBasicBotGame } from "./simulation.js";
export type { SimulationResult } from "./simulation.js";
